DATA:
  DATASET: 'last'
  TRAIN_BATCH: 64
  NUM_INSTANCES: 8
MODEL:
  NAME: resnet50
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  CAL: cal
TRAIN:
  OPTIMIZER:
#    LR: 0.0000003
    LR: 0.00000035
TAG: res50-clip-combiner-last