DATA:
  DATASET: 'vcclothes'
  HEIGHT: 384
  WIDTH: 128
  TRAIN_BATCH: 64
  NUM_INSTANCES: 8
MODEL:
  NAME: resnet50
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  CAL: cal
  PAIR_S: 16.0
TRAIN:
  OPTIMIZER:
#    LR: 0.00000035
    LR: 0.0000035
TAG: res50-clip-combiner-vcclothes
